name: Statistics

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-stats:
    name: Compile stats
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 180
          charts: true
          publish-as: comment
